#!/bin/bash

# =====================================================
# OAUTH CLIENT SECRETS SYNCHRONIZATION SCRIPT
# =====================================================
# Retrieves OAuth2 client secrets from Keycloak and
# updates the .env configuration file to keep secrets
# in sync between Keycloak and the application configuration.
#
# Purpose:
#   When OAuth2 clients are configured in Keycloak, client secrets
#   are generated by Keycloak. This script fetches those secrets
#   and updates the .env file so that test applications can use
#   the correct credentials for authentication.
#
# Process:
#   1. Verifies Keycloak is running and accessible
#   2. Obtains administrative access token
#   3. Retrieves client UUIDs for configured clients
#   4. Fetches client secrets from Keycloak
#   5. Creates backup of current .env file
#   6. Updates .env file with new secrets
#
# Usage:
#   ./update-client-secrets.sh
#
# Requirements:
#   - Keycloak running and configured
#   - Valid .env configuration file
#   - curl and jq installed
#   - OAuth clients already created in Keycloak
# =====================================================

# Load centralized configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config-loader.sh"

echo "========================================"
echo "OAuth Client Secrets Synchronization"
echo "========================================"
echo ""

# Initialize and validate configuration
init_config

# Project root is the parent directory of scripts/
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"

# =====================================================
# PRE-FLIGHT CHECKS
# =====================================================

# -----------------------------------------------------
# Check Keycloak Availability
# -----------------------------------------------------
# Verify that Keycloak is running and accessible before
# attempting to retrieve client secrets
echo "Checking Keycloak availability..."
if ! curl -s "http://$KEYCLOAK_HOST:$KEYCLOAK_PORT/health" > /dev/null 2>&1; then
    echo "ERROR: Keycloak is not running or not accessible"
    echo "HINT: Start services with 'make up' before running this script"
    exit 1
fi
echo "Keycloak is accessible"
echo ""

# =====================================================
# AUTHENTICATION
# =====================================================

# -----------------------------------------------------
# Obtain Administrative Access Token
# -----------------------------------------------------
# Get an access token from Keycloak's master realm
# to perform administrative operations
echo "Obtaining administrative access token..."
ADMIN_TOKEN=$(curl -s -X POST "http://$KEYCLOAK_HOST:$KEYCLOAK_PORT/realms/master/protocol/openid-connect/token" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    -d "grant_type=password" \
    -d "client_id=admin-cli" \
    -d "username=$KEYCLOAK_ADMIN_USER" \
    -d "password=$KEYCLOAK_ADMIN_PASSWORD" | jq -r '.access_token')

if [ "$ADMIN_TOKEN" = "null" ] || [ -z "$ADMIN_TOKEN" ]; then
    echo "ERROR: Failed to obtain admin token"
    echo "HINT: Verify admin credentials in .env file"
    exit 1
fi
echo "Admin token obtained successfully"
echo ""

# =====================================================
# HELPER FUNCTIONS
# =====================================================

# -----------------------------------------------------
# FUNCTION: get_client_secret
# -----------------------------------------------------
# Retrieves the client secret for a given OAuth2 client.
#
# Process:
#   1. Looks up client UUID using client ID
#   2. Fetches client secret using UUID
#
# Parameters:
#   $1 - Client ID (e.g., "test_client1")
#
# Returns:
#   Echoes the client secret on success
#   Returns non-zero exit code on failure
# -----------------------------------------------------
get_client_secret() {
    local client_id="$1"

    # Step 1: Get client UUID
    # Keycloak's internal UUID is required to fetch the secret
    local client_uuid=$(curl -s -X GET "http://$KEYCLOAK_HOST:$KEYCLOAK_PORT/admin/realms/$REALM_NAME/clients?clientId=$client_id" \
        -H "Authorization: Bearer $ADMIN_TOKEN" | jq -r '.[0].id')

    if [ "$client_uuid" = "null" ] || [ -z "$client_uuid" ]; then
        echo "ERROR: Client '$client_id' not found in realm '$REALM_NAME'" >&2
        return 1
    fi

    # Step 2: Get client secret
    local client_secret=$(curl -s -X GET "http://$KEYCLOAK_HOST:$KEYCLOAK_PORT/admin/realms/$REALM_NAME/clients/$client_uuid/client-secret" \
        -H "Authorization: Bearer $ADMIN_TOKEN" | jq -r '.value')

    if [ "$client_secret" = "null" ] || [ -z "$client_secret" ]; then
        echo "ERROR: Failed to retrieve secret for client '$client_id'" >&2
        return 1
    fi

    echo "$client_secret"
}

# =====================================================
# RETRIEVE CLIENT SECRETS
# =====================================================

echo "Retrieving client secrets from Keycloak..."
echo ""

# Fetch secret for first OAuth client
echo "Getting client secret for: $CLIENT_ID1"
NEW_CLIENT_SECRET1=$(get_client_secret "$CLIENT_ID1")
if [ $? -ne 0 ]; then
    exit 1
fi
echo "  Secret retrieved: $NEW_CLIENT_SECRET1"
echo ""

# Fetch secret for second OAuth client
echo "Getting client secret for: $CLIENT_ID2"
NEW_CLIENT_SECRET2=$(get_client_secret "$CLIENT_ID2")
if [ $? -ne 0 ]; then
    exit 1
fi
echo "  Secret retrieved: $NEW_CLIENT_SECRET2"
echo ""

# =====================================================
# UPDATE CONFIGURATION FILE
# =====================================================

echo "Updating .env configuration file..."
echo ""

# Create backup before modifying
# This allows recovery if something goes wrong
cp "$ENV_FILE" "$ENV_FILE.backup"
echo "Backup created: $ENV_FILE.backup"

# -----------------------------------------------------
# Update CLIENT_SECRET1
# -----------------------------------------------------
# Use sed to replace existing value or append if not present
if grep -q "^CLIENT_SECRET1=" "$ENV_FILE"; then
    # Variable exists, update its value
    sed -i.tmp "s/^CLIENT_SECRET1=.*/CLIENT_SECRET1=$NEW_CLIENT_SECRET1/" "$ENV_FILE"
else
    # Variable doesn't exist, append it
    echo "CLIENT_SECRET1=$NEW_CLIENT_SECRET1" >> "$ENV_FILE"
fi

# -----------------------------------------------------
# Update CLIENT_SECRET2
# -----------------------------------------------------
if grep -q "^CLIENT_SECRET2=" "$ENV_FILE"; then
    sed -i.tmp "s/^CLIENT_SECRET2=.*/CLIENT_SECRET2=$NEW_CLIENT_SECRET2/" "$ENV_FILE"
else
    echo "CLIENT_SECRET2=$NEW_CLIENT_SECRET2" >> "$ENV_FILE"
fi

# Clean up temporary files created by sed on macOS
rm -f "$ENV_FILE.tmp"

echo ".env file updated successfully"
echo ""

# =====================================================
# DISPLAY SUMMARY
# =====================================================

echo "========================================"
echo "Synchronization Complete"
echo "========================================"
echo ""
echo "Updated Values:"
echo "  CLIENT_SECRET1=$NEW_CLIENT_SECRET1"
echo "  CLIENT_SECRET2=$NEW_CLIENT_SECRET2"
echo ""
echo "Next Steps:"
echo "  - Restart application containers if needed"
echo "  - Test authentication with updated secrets"
echo ""
